baseURL = "https://tomwarrens.github.io/"
languageCode = "en-us"
title = "Tommaso Guerrini"
theme = "PaperMod"

[params]
  author = "Tommaso Guerrini"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10